version: 1.0.{build}
image: Visual Studio 2019 Preview
configuration: Release
build_script:
- cmd: >-
    git submodule update --init --recursive

    msbuild Vic2ToHoI4.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild Vic2ToHoI4Tests/Vic2ToHoI4Tests-Google.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test_script:
- ps: >-
    vstest.console /logger:Appveyor frontend\Frontend.Core.Tests\bin\Release\Frontend.Core.Tests.dll

    cd Release\Vic2ToHoI4

    ..\..\Vic2ToHoI4Tests\Release\Vic2ToHoI4Tests.exe --gtest_output=xml:tests.xml
artifacts:
- path: Release
  name: Vic2ToHoI4